name:                realcalc
version:             0.1.0.0
github:              "dbramucci/realcalc"
license:             BSD3
author:              "Daniel Bramucci"
maintainer:          "dbramuccicode@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ dbramucci/realcalc#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3.0 && < 1.3
- trifecta >= 2 && < 2.1
- bytestring >= 0.10.8.2 && < 0.11
- filepath >= 1.4.1.2 && < 1.5

library:
  source-dirs: src

executables:
  realcalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realcalc

tests:
  realcalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realcalc
